import { EmployeeTask, TaskStatus, TaskPriority } from '@/types/employee-tasks';
import { addDays, subDays, startOfMonth, endOfMonth, addHours } from 'date-fns';

export const generateDemoTasks = (): EmployeeTask[] => {
  const today = new Date();
  const monthStart = startOfMonth(today);
  const monthEnd = endOfMonth(today);

  return [
    {
      id: 1,
      title: 'إعداد تقرير المبيعات الشهري',
      description: 'إعداد وتجهيز تقرير المبيعات لشهر نوفمبر مع التحليلات والرسوم البيانية',
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.HIGH,
      start_date: subDays(today, 2),
      end_date: addDays(today, 3),
      assigned_by: 'أحمد محمود',
      notes: 'يجب التركيز على مقارنة الأداء مع الشهر الماضي',
    },
    {
      id: 2,
      title: 'متابعة العميل الجديد - شركة الأمل',
      description: 'التواصل مع شركة الأمل بخصوص العرض المقدم ومتابعة رد الشركة',
      status: TaskStatus.TODO,
      priority: TaskPriority.URGENT,
      start_date: today,
      end_date: addDays(today, 1),
      assigned_by: 'سارة أحمد',
      notes: 'العميل طلب موعد للاجتماع يوم الخميس',
    },
    {
      id: 3,
      title: 'تحديث قاعدة بيانات العملاء',
      description: 'مراجعة وتحديث معلومات الاتصال لجميع العملاء في النظام',
      status: TaskStatus.COMPLETED,
      priority: TaskPriority.MEDIUM,
      start_date: subDays(today, 5),
      end_date: subDays(today, 1),
      assigned_by: 'محمد خالد',
      notes: 'تم الانتهاء من تحديث 250 عميل',
    },
    {
      id: 4,
      title: 'تدريب على النظام الجديد',
      description: 'حضور جلسة تدريبية على النظام الجديد لإدارة العملاء',
      status: TaskStatus.TODO,
      priority: TaskPriority.MEDIUM,
      start_date: addDays(today, 5),
      end_date: addDays(today, 5),
      assigned_by: 'قسم الموارد البشرية',
      notes: 'الجلسة في قاعة الاجتماعات الرئيسية - الساعة 10 صباحاً',
    },
    {
      id: 5,
      title: 'مراجعة العقود المنتهية',
      description: 'مراجعة جميع العقود التي ستنتهي خلال الشهر القادم والتواصل مع العملاء',
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.HIGH,
      start_date: subDays(today, 1),
      end_date: addDays(today, 7),
      assigned_by: 'إدارة المبيعات',
      notes: 'يوجد 15 عقد سينتهي قريباً',
    },
    {
      id: 6,
      title: 'إعداد عرض تقديمي للعميل الجديد',
      description: 'تحضير عرض تقديمي شامل لشركة النور بخصوص خدماتنا',
      status: TaskStatus.TODO,
      priority: TaskPriority.HIGH,
      start_date: addDays(today, 2),
      end_date: addDays(today, 4),
      assigned_by: 'مدير التسويق',
      notes: 'التركيز على الحلول الرقمية',
    },
    {
      id: 7,
      title: 'اجتماع الفريق الأسبوعي',
      description: 'اجتماع دوري لمناقشة تقدم العمل والمشاريع الجارية',
      status: TaskStatus.COMPLETED,
      priority: TaskPriority.LOW,
      start_date: subDays(today, 3),
      end_date: subDays(today, 3),
      assigned_by: 'مدير القسم',
    },
    {
      id: 8,
      title: 'إعداد تقرير الأداء الربع سنوي',
      description: 'تجميع وتحليل بيانات الأداء للربع الأخير من السنة',
      status: TaskStatus.ON_HOLD,
      priority: TaskPriority.MEDIUM,
      start_date: addDays(today, 10),
      end_date: addDays(today, 20),
      assigned_by: 'المدير العام',
      notes: 'معلق بانتظار البيانات من قسم المالية',
    },
    {
      id: 9,
      title: 'زيارة ميدانية للعميل - شركة المستقبل',
      description: 'زيارة موقع شركة المستقبل لمناقشة متطلبات المشروع الجديد',
      status: TaskStatus.TODO,
      priority: TaskPriority.HIGH,
      start_date: addDays(today, 8),
      end_date: addDays(today, 8),
      assigned_by: 'مدير المشاريع',
      notes: 'الموعد الساعة 2 ظهراً في مقر الشركة',
    },
    {
      id: 10,
      title: 'متابعة طلبات الدعم الفني',
      description: 'مراجعة والرد على جميع طلبات الدعم الفني المعلقة',
      status: TaskStatus.IN_PROGRESS,
      priority: TaskPriority.URGENT,
      start_date: today,
      end_date: today,
      assigned_by: 'مدير الدعم الفني',
      notes: 'يوجد 8 طلبات تحتاج رد عاجل',
    },
    {
      id: 11,
      title: 'تحليل بيانات السوق',
      description: 'دراسة وتحليل اتجاهات السوق الحالية وإعداد تقرير مفصل',
      status: TaskStatus.TODO,
      priority: TaskPriority.MEDIUM,
      start_date: addDays(today, 15),
      end_date: addDays(today, 25),
      assigned_by: 'قسم البحث والتطوير',
    },
    {
      id: 12,
      title: 'مراجعة الميزانية التسويقية',
      description: 'مراجعة المصروفات التسويقية وإعداد تقرير المقارنة مع الميزانية المخططة',
      status: TaskStatus.COMPLETED,
      priority: TaskPriority.MEDIUM,
      start_date: subDays(today, 7),
      end_date: subDays(today, 2),
      assigned_by: 'المدير المالي',
    },
  ];
};

